BOOTLOADER = rp2040

EXTRAKEY_ENABLE 	= yes
NKRO_ENABLE 		= yes
MOUSEKEY_ENABLE 	= yes
TAP_DANCE_ENABLE    = yes
COMBO_ENABLE        = yes

ENCODER_ENABLE      = yes
RGB_MATRIX_ENABLE   = yes
RGB_MATRIX_DRIVER   = ws2812
WS2812_DRIVER       = vendor