BOOTLOADER = rp2040

BOOTMAGIC_ENABLE    = yes
EXTRAKEY_ENABLE 	= yes
NKRO_ENABLE 		= yes
MOUSEKEY_ENABLE 	= yes
TAP_DANCE_ENABLE    = yes
COMBO_ENABLE        = yes

ENCODER_ENABLE      = yes
DIP_SWITCH_ENABLE   = yes
RGB_MATRIX_ENABLE   = yes
RGB_MATRIX_DRIVER   = ws2812
WS2812_DRIVER       = vendor